#!yaml

# This file is generated by a python script. The script only ADDS new entries to the file. 
# The order of the servers is important here.

# Format: SERVERNAME::SERVERFQDN::ACTION::TIMESTAMP::COMMENT

server_activity_log:
	- 'apple-1-1.vrsl.net::STARTED::123512345134'
	- 'banana-1-1.vrsl.net::STARTED::123512345134'
	- 'cherry-1-1.vrsl.net::STARTED'
	- 'apple-1-2.vrsl.net::STARTED'
	- 'banana-1-2.vrsl.net::STARTED'
	- 'cherry-1-2.vrsl.net::STARTED'
	- 'cherry-1-2.vrsl.net::DELETED'